#!/bin/sh

pwd > "C:/My Dropbox/Programming/BigProjects/C++/GitRPG/raw"
git log --shortstat >> "C:/My Dropbox/Programming/BigProjects/C++/GitRPG/raw"
"C:/My Dropbox/Programming/BigProjects/C++/GitRPG/parse-raw.exe"